CREATE TABLE IF NOT EXISTS user_contexts (
  user_id  TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  org_id   TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
