// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (org_id, name, key_prefix, key_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, key_prefix, created_by, created_at, expires_at
`

type CreateAPIKeyParams struct {
	OrgID     string       `json:"org_id"`
	Name      string       `json:"name"`
	KeyPrefix string       `json:"key_prefix"`
	KeyHash   string       `json:"key_hash"`
	CreatedBy string       `json:"created_by"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID        string       `json:"id"`
	OrgID     string       `json:"org_id"`
	Name      string       `json:"name"`
	KeyPrefix string       `json:"key_prefix"`
	CreatedBy string       `json:"created_by"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.OrgID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, org_id, name, key_prefix, key_hash, created_by, created_at, expires_at, last_used_at, revoked_at
FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByOrg = `-- name: ListAPIKeysByOrg :many
SELECT id, org_id, name, key_prefix, created_by, created_at, expires_at, last_used_at
FROM api_keys
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListAPIKeysByOrgRow struct {
	ID         string       `json:"id"`
	OrgID      string       `json:"org_id"`
	Name       string       `json:"name"`
	KeyPrefix  string       `json:"key_prefix"`
	CreatedBy  string       `json:"created_by"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
}

func (q *Queries) ListAPIKeysByOrg(ctx context.Context, orgID string) ([]ListAPIKeysByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByOrgRow{}
	for rows.Next() {
		var i ListAPIKeysByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.KeyPrefix,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.OrgID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, id)
	return err
}
