// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (org_id, actor_id, action, entity, entity_id, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	OrgID     string                `json:"org_id"`
	ActorID   string                `json:"actor_id"`
	Action    string                `json:"action"`
	Entity    string                `json:"entity"`
	EntityID  string                `json:"entity_id"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT org_id, actor_id, action, entity, entity_id,
       COALESCE(metadata, '{}') AS metadata,
       created_at
FROM audit_logs
WHERE org_id = $1
  AND (CAST($2 AS text) IS NULL OR actor_id = CAST($2 AS text))
  AND (CAST($3 AS text) IS NULL OR action = CAST($3 AS text))
  AND (CAST($4 AS text) IS NULL OR entity = CAST($4 AS text))
  AND (CAST($5 AS timestamptz) IS NULL OR created_at >= CAST($5 AS timestamptz))
  AND (CAST($6 AS timestamptz) IS NULL OR created_at <= CAST($6 AS timestamptz))
ORDER BY created_at DESC
LIMIT $8 OFFSET $7
`

type ListAuditLogsParams struct {
	OrgID         string         `json:"org_id"`
	FilterActorID sql.NullString `json:"filter_actor_id"`
	FilterAction  sql.NullString `json:"filter_action"`
	FilterEntity  sql.NullString `json:"filter_entity"`
	FilterSince   sql.NullTime   `json:"filter_since"`
	FilterUntil   sql.NullTime   `json:"filter_until"`
	QueryOffset   int32          `json:"query_offset"`
	QueryLimit    int32          `json:"query_limit"`
}

type ListAuditLogsRow struct {
	OrgID     string          `json:"org_id"`
	ActorID   string          `json:"actor_id"`
	Action    string          `json:"action"`
	Entity    string          `json:"entity"`
	EntityID  string          `json:"entity_id"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.OrgID,
		arg.FilterActorID,
		arg.FilterAction,
		arg.FilterEntity,
		arg.FilterSince,
		arg.FilterUntil,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
