// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (org_id, actor_id, action, entity, entity_id, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	OrgID     string                `json:"org_id"`
	ActorID   string                `json:"actor_id"`
	Action    string                `json:"action"`
	Entity    string                `json:"entity"`
	EntityID  string                `json:"entity_id"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT org_id, actor_id, action, entity, entity_id,
       COALESCE(metadata, '{}') AS metadata,
       created_at
FROM audit_logs
WHERE org_id = $1
  AND ($2::text IS NULL OR actor_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::text IS NULL OR entity = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $7 OFFSET $8
`

type ListAuditLogsParams struct {
	OrgID   string    `json:"org_id"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 string    `json:"column_4"`
	Column5 time.Time `json:"column_5"`
	Column6 time.Time `json:"column_6"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListAuditLogsRow struct {
	OrgID     string          `json:"org_id"`
	ActorID   string          `json:"actor_id"`
	Action    string          `json:"action"`
	Entity    string          `json:"entity"`
	EntityID  string          `json:"entity_id"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
