// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const deleteFile = `-- name: DeleteFile :execresult
DELETE FROM files
WHERE id = $1 AND org_id = $2
`

type DeleteFileParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFile, arg.ID, arg.OrgID)
}

const getFile = `-- name: GetFile :one
SELECT id, org_id, uploaded_by, bucket, object_key, size_bytes, content_type, created_at, metadata
FROM files
WHERE id = $1 AND org_id = $2
`

type GetFileParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.ID, arg.OrgID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.Bucket,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (id, org_id, uploaded_by, bucket, object_key, size_bytes, content_type, created_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, uploaded_by, bucket, object_key, size_bytes, content_type, created_at, metadata
`

type InsertFileParams struct {
	ID          string                `json:"id"`
	OrgID       string                `json:"org_id"`
	UploadedBy  string                `json:"uploaded_by"`
	Bucket      string                `json:"bucket"`
	ObjectKey   string                `json:"object_key"`
	SizeBytes   sql.NullInt64         `json:"size_bytes"`
	ContentType sql.NullString        `json:"content_type"`
	CreatedAt   time.Time             `json:"created_at"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile,
		arg.ID,
		arg.OrgID,
		arg.UploadedBy,
		arg.Bucket,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentType,
		arg.CreatedAt,
		arg.Metadata,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.Bucket,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentType,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, org_id, uploaded_by, bucket, object_key, size_bytes, content_type, created_at, metadata
FROM files
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFilesParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UploadedBy,
			&i.Bucket,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentType,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
