// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteMember, arg.OrgID, arg.UserID)
	return err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role
FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMemberRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const updateMemberRole = `-- name: UpdateMemberRole :execresult
UPDATE memberships
SET role = $3
WHERE org_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMemberRole, arg.OrgID, arg.UserID, arg.Role)
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertMemberParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}
