// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID         string       `json:"id"`
	OrgID      string       `json:"org_id"`
	Name       string       `json:"name"`
	KeyPrefix  string       `json:"key_prefix"`
	KeyHash    string       `json:"key_hash"`
	CreatedBy  string       `json:"created_by"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type AuditLog struct {
	ID        int64                 `json:"id"`
	OrgID     string                `json:"org_id"`
	ActorID   string                `json:"actor_id"`
	Action    string                `json:"action"`
	Entity    string                `json:"entity"`
	EntityID  string                `json:"entity_id"`
	CreatedAt time.Time             `json:"created_at"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

type File struct {
	ID          string                `json:"id"`
	OrgID       string                `json:"org_id"`
	UploadedBy  string                `json:"uploaded_by"`
	Bucket      string                `json:"bucket"`
	ObjectKey   string                `json:"object_key"`
	SizeBytes   sql.NullInt64         `json:"size_bytes"`
	ContentType sql.NullString        `json:"content_type"`
	CreatedAt   time.Time             `json:"created_at"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type Membership struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
	Role   string `json:"role"`
}

type Organization struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	OwnerUserID string    `json:"owner_user_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Project struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RefreshToken struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	TokenHash   string         `json:"token_hash"`
	ExpiresAt   time.Time      `json:"expires_at"`
	RevokedAt   sql.NullTime   `json:"revoked_at"`
	RotatedFrom sql.NullString `json:"rotated_from"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserContext struct {
	UserID    string    `json:"user_id"`
	OrgID     string    `json:"org_id"`
	UpdatedAt time.Time `json:"updated_at"`
}
