// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orgs.sql

package repo

import (
	"context"
	"time"
)

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOrg, id)
	return err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, owner_user_id, created_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrg, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrg = `-- name: InsertOrg :exec
INSERT INTO organizations (id, name, owner_user_id, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertOrgParams struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	OwnerUserID string    `json:"owner_user_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertOrg(ctx context.Context, arg InsertOrgParams) error {
	_, err := q.db.ExecContext(ctx, insertOrg,
		arg.ID,
		arg.Name,
		arg.OwnerUserID,
		arg.CreatedAt,
	)
	return err
}
