// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getPasswordResetByHash = `-- name: GetPasswordResetByHash :one
SELECT id, user_id, token_hash, expires_at, used_at
FROM password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL
`

type GetPasswordResetByHashRow struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

func (q *Queries) GetPasswordResetByHash(ctx context.Context, tokenHash string) (GetPasswordResetByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByHash, tokenHash)
	var i GetPasswordResetByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
