// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteProject = `-- name: DeleteProject :execresult
DELETE FROM projects
WHERE id = $1 AND org_id = $2
`

type DeleteProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProject, arg.ID, arg.OrgID)
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, description, created_by, created_at, updated_at
FROM projects
WHERE id = $1 AND org_id = $2
`

type GetProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (id, org_id, name, description, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, org_id, name, description, created_by, created_at, updated_at
`

type InsertProjectParams struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   string         `json:"created_by"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, name, description, created_by, created_at, updated_at
FROM projects
WHERE org_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProjects(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE(NULLIF($3, ''), name),
    description = $4,
    updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, created_by, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Column3     interface{}    `json:"column_3"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ID,
		arg.OrgID,
		arg.Column3,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
