// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT user_id, token_hash, expires_at, revoked_at
FROM refresh_tokens
WHERE id = $1
`

type GetRefreshTokenRow struct {
	UserID    string       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, id string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, rotated_from)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	TokenHash   string         `json:"token_hash"`
	ExpiresAt   time.Time      `json:"expires_at"`
	RotatedFrom sql.NullString `json:"rotated_from"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RotatedFrom,
	)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, id)
	return err
}
