// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repo

import (
	"context"
	"database/sql"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions
SET status = 'canceled', updated_at = now()
WHERE stripe_subscription_id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, stripeSubscriptionID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, cancelSubscription, stripeSubscriptionID)
	return err
}

const getSubscriptionByOrg = `-- name: GetSubscriptionByOrg :one
SELECT id, org_id, stripe_customer_id, stripe_subscription_id, status, plan, current_period_end, created_at, updated_at
FROM subscriptions
WHERE org_id = $1
`

func (q *Queries) GetSubscriptionByOrg(ctx context.Context, orgID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByOrg, orgID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByStripeCustomer = `-- name: GetSubscriptionByStripeCustomer :one
SELECT id, org_id, stripe_customer_id, stripe_subscription_id, status, plan, current_period_end, created_at, updated_at
FROM subscriptions
WHERE stripe_customer_id = $1
`

func (q *Queries) GetSubscriptionByStripeCustomer(ctx context.Context, stripeCustomerID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByStripeCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $2, plan = $3, current_period_end = $4, updated_at = now()
WHERE stripe_subscription_id = $1
`

type UpdateSubscriptionStatusParams struct {
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	Status               string         `json:"status"`
	Plan                 string         `json:"plan"`
	CurrentPeriodEnd     sql.NullTime   `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.Plan,
		arg.CurrentPeriodEnd,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (org_id, stripe_customer_id, stripe_subscription_id, status, plan, current_period_end)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id) DO UPDATE SET
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    status = EXCLUDED.status,
    plan = EXCLUDED.plan,
    current_period_end = EXCLUDED.current_period_end,
    updated_at = now()
`

type UpsertSubscriptionParams struct {
	OrgID                string         `json:"org_id"`
	StripeCustomerID     string         `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	Status               string         `json:"status"`
	Plan                 string         `json:"plan"`
	CurrentPeriodEnd     sql.NullTime   `json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription,
		arg.OrgID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.Plan,
		arg.CurrentPeriodEnd,
	)
	return err
}
