// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_contexts.sql

package repo

import (
	"context"
)

const getActiveOrg = `-- name: GetActiveOrg :one
SELECT org_id
FROM user_contexts
WHERE user_id = $1
`

func (q *Queries) GetActiveOrg(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrg, userID)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const upsertActiveOrg = `-- name: UpsertActiveOrg :exec
INSERT INTO user_contexts (user_id, org_id, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id) DO UPDATE
SET org_id = $2, updated_at = NOW()
`

type UpsertActiveOrgParams struct {
	UserID string `json:"user_id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) UpsertActiveOrg(ctx context.Context, arg UpsertActiveOrgParams) error {
	_, err := q.db.ExecContext(ctx, upsertActiveOrg, arg.UserID, arg.OrgID)
	return err
}
