// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (org_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, url, events, active, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	OrgID  string   `json:"org_id"`
	Url    string   `json:"url"`
	Secret string   `json:"secret"`
	Events []string `json:"events"`
}

type CreateWebhookEndpointRow struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	Url       string    `json:"url"`
	Events    []string  `json:"events"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (CreateWebhookEndpointRow, error) {
	row := q.db.QueryRowContext(ctx, createWebhookEndpoint,
		arg.OrgID,
		arg.Url,
		arg.Secret,
		pq.Array(arg.Events),
	)
	var i CreateWebhookEndpointRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveEndpointsForEvent = `-- name: GetActiveEndpointsForEvent :many
SELECT id, org_id, url, secret, events
FROM webhook_endpoints
WHERE org_id = $1 AND active AND $2 = ANY(events)
`

type GetActiveEndpointsForEventParams struct {
	OrgID  string   `json:"org_id"`
	Events []string `json:"events"`
}

type GetActiveEndpointsForEventRow struct {
	ID     string   `json:"id"`
	OrgID  string   `json:"org_id"`
	Url    string   `json:"url"`
	Secret string   `json:"secret"`
	Events []string `json:"events"`
}

func (q *Queries) GetActiveEndpointsForEvent(ctx context.Context, arg GetActiveEndpointsForEventParams) ([]GetActiveEndpointsForEventRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveEndpointsForEvent, arg.OrgID, pq.Array(arg.Events))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveEndpointsForEventRow{}
	for rows.Next() {
		var i GetActiveEndpointsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Secret,
			pq.Array(&i.Events),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingDeliveries = `-- name: GetPendingDeliveries :many
SELECT d.id, d.endpoint_id, d.event, d.payload, d.attempts,
       e.url, e.secret
FROM webhook_deliveries d
JOIN webhook_endpoints e ON e.id = d.endpoint_id
WHERE NOT d.delivered AND d.attempts < 5 AND d.next_retry <= now()
ORDER BY d.next_retry
LIMIT $1
`

type GetPendingDeliveriesRow struct {
	ID         string          `json:"id"`
	EndpointID string          `json:"endpoint_id"`
	Event      string          `json:"event"`
	Payload    json.RawMessage `json:"payload"`
	Attempts   int32           `json:"attempts"`
	Url        string          `json:"url"`
	Secret     string          `json:"secret"`
}

func (q *Queries) GetPendingDeliveries(ctx context.Context, limit int32) ([]GetPendingDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingDeliveriesRow{}
	for rows.Next() {
		var i GetPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.Event,
			&i.Payload,
			&i.Attempts,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, org_id, url, secret, events, active, created_at, updated_at
FROM webhook_endpoints
WHERE id = $1 AND org_id = $2
`

type GetWebhookEndpointParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpoint, arg.ID, arg.OrgID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO webhook_deliveries (endpoint_id, event, payload, next_retry)
VALUES ($1, $2, $3, now())
RETURNING id
`

type InsertDeliveryParams struct {
	EndpointID string          `json:"endpoint_id"`
	Event      string          `json:"event"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertDelivery, arg.EndpointID, arg.Event, arg.Payload)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, org_id, url, events, active, created_at, updated_at
FROM webhook_endpoints
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListWebhookEndpointsRow struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	Url       string    `json:"url"`
	Events    []string  `json:"events"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, orgID string) ([]ListWebhookEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpoints, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookEndpointsRow{}
	for rows.Next() {
		var i ListWebhookEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			pq.Array(&i.Events),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDelivered = `-- name: MarkDelivered :exec
UPDATE webhook_deliveries
SET delivered = true, status_code = $2, response = $3, attempts = attempts + 1
WHERE id = $1
`

type MarkDeliveredParams struct {
	ID         string         `json:"id"`
	StatusCode sql.NullInt32  `json:"status_code"`
	Response   sql.NullString `json:"response"`
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markDelivered, arg.ID, arg.StatusCode, arg.Response)
	return err
}

const markRetry = `-- name: MarkRetry :exec
UPDATE webhook_deliveries
SET attempts = attempts + 1, status_code = $2, response = $3, next_retry = $4
WHERE id = $1
`

type MarkRetryParams struct {
	ID         string         `json:"id"`
	StatusCode sql.NullInt32  `json:"status_code"`
	Response   sql.NullString `json:"response"`
	NextRetry  sql.NullTime   `json:"next_retry"`
}

func (q *Queries) MarkRetry(ctx context.Context, arg MarkRetryParams) error {
	_, err := q.db.ExecContext(ctx, markRetry,
		arg.ID,
		arg.StatusCode,
		arg.Response,
		arg.NextRetry,
	)
	return err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :exec
UPDATE webhook_endpoints
SET url = $3, events = $4, active = $5, updated_at = now()
WHERE id = $1 AND org_id = $2
`

type UpdateWebhookEndpointParams struct {
	ID     string   `json:"id"`
	OrgID  string   `json:"org_id"`
	Url    string   `json:"url"`
	Events []string `json:"events"`
	Active bool     `json:"active"`
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookEndpoint,
		arg.ID,
		arg.OrgID,
		arg.Url,
		pq.Array(arg.Events),
		arg.Active,
	)
	return err
}
